import '../../domain/models/ride.dart';
import '../../domain/repositories/ride_repository.dart';
import '../datasources/ride_remote_data_source.dart';
import '../models/ride_model.dart';

class RideRepositoryImpl implements RideRepository {
  final RideRemoteDataSource remoteDataSource;

  RideRepositoryImpl(this.remoteDataSource);

  @override
  Future<void> createRide({
    required double originLat,
    required double originLng,
    required double destLat,
    required double destLng,
  }) async {
    final rideModel = RideModel(
      id: '', // Will be generated by Supabase
      userId: 'user_demo',
      originLat: originLat,
      originLng: originLng,
      destLat: destLat,
      destLng: destLng,
      status: 'waiting',
    );
    await remoteDataSource.createRide(rideModel);
  }

  @override
  Future<List<Ride>> getRides() async {
    return await remoteDataSource.getRides();
  }
}
